$os = "ubuntu2004arm"
$num_instances = 2
$instance_name_prefix = "k8s"
$vm_memory = 4096
$vm_cpus = 4
$subnet = "172.18.8"
#$subnetHost = "172.16.100"
$etcd_instances = 1
$kube_master_instances = 1
$kube_node_instances = 1
#$ansible_tags = ["etchosts", "dashboard", "metrics_server", "ingress-controller", "facts", "cert-manager", "helm"]
$ansible_tags = ["apps", "ingress-controller"]
$inventory = "inventory/mycluster"
